### ISSUE TITLE
本地规则怎么用啊，还有里面的rule的地址，路径怎么设置啊，谢谢

### ISSUE THREAD

**Issue by rangluwme** [Mythologyli/ZJU-Rule#10]
rt
![image](https://user-images.githubusercontent.com/63960943/187596625-2056d84c-d625-4b0e-b2ae-75d25099c6ec.png)
就是类似于这种，想自己设置，存放在本地。

**Comment by rangluwme** [comment]
我了解clash的设置，只是这个方面不了解，所以来请教。

**Comment by Mythologyli** [comment]
这些规则不是直接给 Clash 使用的，是给 [subconverter](https://github.com/tindy2013/subconverter) 使用的。
subconverter 网上的教程很多，如果不明白的话，可以加 README 里的电报群，在群里 at 我。
