### ISSUE TITLE
请求增加一个直连域名

### ISSUE THREAD

**Issue by Simoncatty** [Mythologyli/ZJU-Rule#11]
请求增加
https://pubs.geoscienceworld.org/
这个进行直连，方便下载文献

**Comment by Mythologyli** [comment]
感谢贡献！
请问这个数据库的订阅信息有在学校哪个网站公示吗？浙大图书馆的[数据库导航网站](http://210.32.137.90/s/lib/libtb/)里似乎没有。

**Comment by Simoncatty** [comment]
感谢

应该是
http://210.32.137.90/s/lib/libtb/show/456
这个下属的一个订阅，
https://www.nstl.gov.cn/help/zyyfw_qwwx.html
在期刊的官网上显示的为
Zhejiang University
NSTL

**Comment by Mythologyli** [comment]
NSTL 中的所有资源已添加，感谢贡献！
