### ISSUE TITLE
关于web of science代理的问题

### ISSUE THREAD

**Issue by tangjyan** [Mythologyli/ZJU-Rule#12]
我设置了和web of science相关的所有域名
- DOMAIN-SUFFIX,clarivate.com,🎯 全球直连
- DOMAIN-SUFFIX,webofknowledge.com,🎯 全球直连
- DOMAIN-SUFFIX,isiknowledge.com,🎯 全球直连
- DOMAIN-SUFFIX,webofscience.com,🎯 全球直连

可是打开 https://www.webofscience.com/ 还是显示我用的代理访问而非直连，请问是wos内部做了什么跳转吗？

**Comment by Mythologyli** [comment]
webofscience.com 已在 ZJU 内网规则内，我在浙江大学校园网环境下测试，可以正常下载
你的网络环境是什么？

另外，需要确保你添加的 DOMAIN-SUFFIX 位置靠前，因为假如 URL 同时匹配两个规则，只有行数靠前的规则生效

**Comment by tangjyan** [comment]
我重新测试了一下，用win 客户端是没问题的。我目前用的是padavan路由器，应该是路由器上的配置问题，谢谢你的回复
