### ISSUE TITLE
生成的订阅链接倒入到clash中后下载失败

### ISSUE THREAD

**Issue by fulj** [Mythologyli/ZJU-Rule#15]

**Comment by Mythologyli** [comment]
确保关闭主界面 System Proxy，然后再次尝试下载订阅
如果仍然失败，可以把原订阅链接发送至我的邮箱 [myth@myth.cx](mailto:myth@myth.cx)

**Comment by fulj** [comment]
原链接：https://api.huacloud.xyz/sub?target=clash&amp;insert=true&amp;emoji=true&amp;udp=true&amp;clash.doh=true&amp;new_name=true&amp;filename=Flower_SS&amp;url=https%3A%2F%2Fapi.flowercloud.xyz%2Fosubscribe.php%3Fsid%3D22019%26token%3DSZTUP8qo%26sip002%3D1


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mythologyli/ZJU-Rule"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月15日(星期四) 晚上7:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mythologyli/ZJU-Rule] 生成的订阅链接倒入到clash中后下载失败 (Issue #15)





 
确保关闭主界面 System Proxy，然后再次尝试下载订阅
 如果仍然失败，可以把原订阅链接发送至我的邮箱 ***@***.***

**Comment by Mythologyli** [comment]
https://sub.zjurule.xyz/sub?target=clash&url=https%3A%2F%2Fapi.flowercloud.xyz%2Fosubscribe.php%3Fsid%3D22019%26token%3DSZTUP8qo%26sip002%3D1&insert=false&emoji=true&list=false&tfo=false&scv=true&fdn=false&sort=false&new_name=true
