### ISSUE TITLE
请求增加一个直连域名 -- yuque

### ISSUE THREAD

**Issue by dzh929** [Mythologyli/ZJU-Rule#21]
https://www.yuque.com/

**Comment by dzh929** [comment]
大佬平时用语雀比较多，不希望它走代理，会比较慢，是选直连还是内网，想要加到规则里，这样就不用每次都自己添加了

**Comment by Mythologyli** [comment]
![image](https://user-images.githubusercontent.com/15955880/225191343-44be3332-5887-4293-9f51-9860d9fcb965.png)

应该本来就是直连的，你再确认一下？

**Comment by dzh929** [comment]
好的，谢谢
