### ISSUE TITLE
这个有什么用嘛

### ISSUE THREAD

**Issue by p81sunshine** [Mythologyli/ZJU-Rule#26]
不懂就问，这个rule和我梯子的rule的区别是啥？优势在什么地方？为什么需要它？

**Comment by Mythologyli** [comment]
https://www.cc98.org/topic/5257184

**Comment by p81sunshine** [comment]
看到了，感谢！但我感觉glados的梯子，开rule模式，访问校网资源也没啥问题哈。
> 想看 b 站港澳台限定内容，但不知道如何用代理访问，或者只能开启全局模式
b站还有港澳台限定内容！？
> 我的机场提供了 Clash 订阅，但是不和我心意！
不知道这个具体指的是什么？

感谢校友回复~

**Comment by Mythologyli** [comment]
> b站还有港澳台限定内容！？

有的

> 不知道这个具体指的是什么？

指的是有人可能需要一份更全能的规则，例如 ZJU Rule 提供的广告屏蔽、ChatBot（ChatGPT、New Bing）分流等等

另外，ZJU Rule 的用途还包括：在访问浙大购买的学术数据库时直连，避免无法通过 IP 认证
