### ISSUE TITLE
有的订阅链接无法导入，有什么其他解决方案吗？

### ISSUE THREAD

**Issue by ZhenhongDu** [Mythologyli/ZJU-Rule#29]
你好，原始链接可以导入，但是转化后的链接无法导入，可以帮我看下吗

**Comment by ZhenhongDu** [comment]
https://wogame.dev/api/v1/client/subscribe?token=6da4e4254ed5821e8622a974c5a8063e

**Comment by ZhenhongDu** [comment]
zju转化后，可以在浏览器打开，但是clash无法导入
https://sub.zjurule.xyz/sub?target=clash&url=https%3A%2F%2Fwogame.dev%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D6da4e4254ed5821e8622a974c5a8063e&insert=false

**Comment by Mythologyli** [comment]
原始订阅不包含节点，检查订阅是否过期

**Comment by ZhenhongDu** [comment]
哦哦，明白了，很奇怪，但是在机场网页直接导入到clash是可以的，谢谢啦

**Comment by Mythologyli** [comment]
直接访问订阅链接，显示“遇到了些问题，我们正在进行处理”，可能是机场出现故障

**Comment by Mythologyli** [comment]
直接导入 clash，发现无可用节点，机场问题
