### ISSUE TITLE
关于steam下载损失速度的问题

### ISSUE THREAD

**Issue by sqx626** [Mythologyli/ZJU-Rule#30]
steamserver.net代理，steamcontent直连的情况，下载流量确实是没有走代理，但是下载速度损失非常大，稳定性也变得很差，不清楚是为什么qaq

**Comment by Mythologyli** [comment]
可能是下载服务器选择了国外的？可以截图在 log 里看看下载服务器的域名

**Comment by Mythologyli** [comment]
已经同步了上游 ACL4SSR 的最新规则，可以再试试有没有问题

**Comment by Mythologyli** [comment]
暂时关闭 issue，如有新发现可以留言后 reopen
