### ISSUE TITLE
请求添加onlinelibrary.wiley.com至代理

### ISSUE THREAD

**Issue by cxz66666** [Mythologyli/ZJU-Rule#33]
wiley.com目前属于ZJU内网分组，可以正常访问，但onlinelibrary.wiley.com 疑似被阻断(https://ping.pe/onlinelibrary.wiley.com)  ， 请求将其转入ZJU More Scholar 分组

**Comment by Mythologyli** [comment]
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/0cb9d1fd-c266-4c9f-91f0-afa225556c46)
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/b946798e-c182-4cea-ba10-1cb18062189f)

在校内是可以直连访问的。感觉校内走教育网没问题的。

自己的两台境内服务器试了一下也都没有问题。
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/21f9f653-b422-41fb-8e96-11169b3aa85c)
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/d785baa5-c506-49cc-9177-6a43bf89031f)

onlinelibrary.wiley.com 套了 cloudflare cdn，按理说是可以访问的，要不再观察一下？

**Comment by Mythologyli** [comment]
https://ping.pe/162.159.129.87

改成 IP 就没问题了，会不会是 DNS 污染？
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/0262f4db-98f8-4c74-bf1b-504833299d43)

**Comment by cxz66666** [comment]
看起来是cf的任播导致你这边拿到的是162.159.129.87这个ip，没有被封锁，我这边拿到了162.159.130.87 😢

**Comment by Mythologyli** [comment]
162.159.130.87 貌似已经被墙了，162.159.129.87 还活着。
wiley.com 可以使用统一认证登录吗？可以的话就考虑移动至 ZJU More Scholar 分组

**Comment by cxz66666** [comment]
可以使用的 👍

**Comment by Mythologyli** [comment]
已移动，更新订阅即可生效
