### ISSUE TITLE
我复制了glados还有west data买的两个vpn但都不能登校网

### ISSUE THREAD

**Issue by teddyab666** [Mythologyli/ZJU-Rule#39]
<img width="585" alt="微信图片_20230922225504" src="https://github.com/Mythologyli/ZJU-Rule/assets/96061852/e48875e1-f8d2-4e70-b597-fe15decb8abf">
<img width="508" alt="image" src="https://github.com/Mythologyli/ZJU-Rule/assets/96061852/01978f8e-fdd9-4133-a190-f67a114ed705">

**Comment by Mythologyli** [comment]
你目前在校内吗

**Comment by teddyab666** [comment]
嗯~在校内上课的，但是在校外尝试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月22日(周五) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Mythologyli/ZJU-Rule] 我复制了glados还有west data买的两个vpn但都不能登校网 (Issue #39)




 
你目前在校内吗

**Comment by Mythologyli** [comment]
ZJU Rule 规则只会将 ZJU 那一部分直连，具体能不能上取决于你是不是在使用校园网，不能替代 RVPN 的作用

你可以尝试配合 [ZJU Connect](https://github.com/Mythologyli/ZJU-Connect-for-Windows) 一起使用：https://www.cc98.org/topic/5521873
