### ISSUE TITLE
ZJU内网问题

### ISSUE THREAD

**Issue by JIN-strong** [Mythologyli/ZJU-Rule#40]
clash规则选择ZJU内网后，开启代理模式下，依旧无法访问校内内网。

坐标yq，有线网，固定ip，无需登录

**Comment by Mythologyli** [comment]
具体是哪些网站无法访问，请给出无法访问的截图

**Comment by JIN-strong** [comment]
> 具体是哪些网站无法访问，请给出无法访问的截图

所有内网均无法访问，包括但不限于计院院网、图书馆

![image](https://github.com/Mythologyli/ZJU-Rule/assets/54224486/370a214f-7888-4c69-8b41-baa5c46c177f)
这是我的配置图

![image](https://github.com/Mythologyli/ZJU-Rule/assets/54224486/2b17649b-a863-4bec-8705-1768d14a15f1)
这是我的日志截图

**Comment by Mythologyli** [comment]
怀疑是 TUN 模式的 DNS 配置问题

检查一下 cc98 能否访问

**Comment by JIN-strong** [comment]
> 怀疑是 TUN 模式的 DNS 配置问题
> 
> 检查一下 cc98 能否访问

CC98可以访问，且未使用ZJU Rule前也可以在代理模式下访问

**Comment by Mythologyli** [comment]
看来是 TUN 模式的问题
点击 TUN 模式旁的配置图标，将 DNS 设置为 10.10.0.21

**Comment by JIN-strong** [comment]
确实是这个问题，不过添加了DNS服务器后，貌似不用ZJU Rule也会正确解析出ip地址

**Comment by Mythologyli** [comment]
> 确实是这个问题，不过添加了DNS服务器后，貌似不用ZJU Rule也会正确解析出ip地址

ZJU Rule 跟解析 IP 没关系，这只是一个分流规则
