### ISSUE TITLE
Subconverter failed

### ISSUE THREAD

**Issue by futuretech6** [Mythologyli/ZJU-Rule#43]
The URL `https://sub.zjurule.xyz/sub?target=clash&url=$CONFIG_URL` will return the message `The following link doesn't contain any valid node info: $CONFIG_URL`. However, accessing `$CONFIG_URL` directly will provide the correct configuration file.

**Comment by Mythologyli** [comment]
多半是源服务器有 IP 地区等限制导致的，TG 群私聊我，或者联系方式发我邮箱：myth@myth.cx
