### ISSUE TITLE
请问支持生成 shadowrocket 支持订阅链接吗

### ISSUE THREAD

**Issue by Orwell-Yu** [Mythologyli/ZJU-Rule#44]

**Comment by Mythologyli** [comment]
![image](https://github.com/Mythologyli/ZJU-Rule/assets/15955880/d3595f50-eb59-424d-b943-1055720fca4a)

客户端选 SS 试试？

不过还是推荐配合 Clash 使用，不然本仓库的规则就没有意义了

**Comment by Mythologyli** [comment]
不好意思看错了（

**Comment by Mythologyli** [comment]
看了一下，应该是不支持的 https://github.com/tindy2013/subconverter/issues/486

不过作者的文档里是这样写的：https://tindy2013.gitbook.io/subconverter/yue-qian-ti-shi/shi-yong-fan-wei

> 注意：Shadowrocket 用户可以使用 ss、ssr以及 v2ray参数

可以尝试一下，把得到的 url 中的 target 改成上面这几个试试

**Comment by Orwell-Yu** [comment]
好的，感谢阿梓喵（

**Comment by Mythologyli** [comment]
方便反馈下结果嘛

**Comment by Orwell-Yu** [comment]
这三种格式配合我是用的`glados`订阅链接和`ios`端`shadowrocket`都不支持（
