### ISSUE TITLE
请求添加http://210.32.137.90/ 至ZJU内网

### ISSUE THREAD

**Issue by Sam-zcl** [Mythologyli/ZJU-Rule#45]
[http://210.32.137.90/s/lib/libtb/](http://210.32.137.90/s/lib/libtb/)
请求添加图书馆数据库导航至ZJU内网，目前使用ZJU rule + clash 时 连接该网址报 HTTP ERROR 502
![image](https://github.com/Mythologyli/ZJU-Rule/assets/44527431/b61f24d3-ef17-4d76-b4f4-12cde002a592)

若是我的配置问题，也麻烦指正。谢谢！

**Comment by Mythologyli** [comment]
感觉提出，已修复！
