### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yishispace** [Mythologyli/ZJU-Rule#9]
![图片](https://user-images.githubusercontent.com/86669845/166637070-15c2a3f8-8489-4ad4-9702-b654ad07c3a2.png)
错误：HTTP响应状态代码（400）
error: HTTP Response Status Code(400)

**Comment by Mythologyli** [comment]
I just tested it and found no errors.
You can try opening the URL in your web browser. If it doesn't open, try changing your network conditions.
If you still cannot access the service, please contact me in our forum.
